import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import AuthProvider from "@/app/AuthProvider"
import { Toaster } from "sonner";
import { TaskListPreferencesProvider } from "@/utils/hooks/TaskListPreferencesContext";
import FilterResetWatcher from "@/components/FilterResetWatcher";
import AppRefreshProvider from "@/components/providers/AppRefreshProvider";
import { RuleProvider } from "@/components/rule/RuleProvider";
import { TaskUnreadProvider } from "@/components/TaskUnreadProvider";
import ThemeProvider from "@/components/providers/ThemeProvider"
import AppShell from "@/components/layout/AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "タスク管理アプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased m-0 w-full bg-neutral-100 text-neutral-700 dark:bg-[#222222] dark:text-neutral-100`}
      >
        <ThemeProvider>
          <AppRefreshProvider> {/* アプリ非アクティブ時間チェック */}
            <AuthProvider> {/* ユーザーデータ */}
              <TaskListPreferencesProvider> {/* タスクリスト全般 */}
                <RuleProvider> {/* 掲示板更新管理 */}
                  <TaskUnreadProvider> {/* 未読フラグ管理 */}
                    <FilterResetWatcher /> {/* フィルタリセット */}
                    <AppShell>
                      {children}
                    </AppShell>
                    {/* <TaskNotesViewer /> */}
                  </TaskUnreadProvider>
                </RuleProvider>
              </TaskListPreferencesProvider>
            </AuthProvider>
          </AppRefreshProvider>
          <Toaster position="top-center" richColors closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
