import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/app/AuthProvider"
import Header from "@/components/Header";
import { Toaster } from "sonner";
import { TaskListPreferencesProvider } from "@/utils/hooks/TaskListPreferencesContext";
import FilterResetWatcher from "@/components/FilterResetWatcher";
import VersionCheckProvider from "./VersionCheckProvider";
import TaskNotesViewer from "@/components/TaskNotesViewer";
import { RuleProvider } from "@/components/rule/RuleProvider";
import { TaskUnreadProvider } from "@/components/TaskUnreadProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "タスク管理アプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#222222] m-0 w-full`}
      >
        <VersionCheckProvider>{/* バージョンチェック */}
          <AuthProvider>{/* ユーザーデータ */}
            <TaskListPreferencesProvider>{/* タスクリスト全般 */}
              <RuleProvider>{/* 掲示板 */}
                <TaskUnreadProvider>
                  <FilterResetWatcher />
                  <Header />
                  {children}
                  {/* <TaskNotesViewer /> */}
                </TaskUnreadProvider>
              </RuleProvider>
            </TaskListPreferencesProvider>
          </AuthProvider>
        </VersionCheckProvider>
        <Toaster position="bottom-right" richColors closeButton />
      </body>
    </html>
  );
}
